config/routes.rb
Hyrax::Engine.routes.draw do
  # Downloads controller route
  resources :homepage, only: 'index'

  # Route the home page as the root
  root to: 'homepage#index'

  # Handle routes that existed in Hyrax < 7
  #   e.g. https://scholarsphere.psu.edu/files/gm80hv36p
  get '/files/:id', to: redirect('/concern/generic_works/%{id}')

  resources :downloads, only: :show

  # ResourceSync routes
  get '/.well-known/resourcesync' => 'resource_sync#source_description', as: :source_description
  get '/capabilitylist' => 'resource_sync#capability_list', as: :capability_list
  get '/resourcelist' => 'resource_sync#resource_list', as: :resource_list
  get '/changelist' => 'resource_sync#change_list', as: :change_list

  delete '/uploads/:id', to: 'uploads#destroy', as: :uploaded_file
  post '/uploads', to: 'uploads#create'
  # This is a hack that is required because the rails form the uploader is on
  # sets the _method parameter to patch when the work already exists.
  # Eventually it would be good to update the javascript so that it doesn't
  # submit the form, just the file and always uses POST.
  patch '/uploads', to: 'uploads#create'

  match 'batch_edits/clear' => 'batch_edits#clear', as: :batch_edits_clear, via: [:get, :post]
  resources :batch_edits, only: [:index] do
    member do
      delete :destroy
    end
    collection do
      get :index
      get :edit
      put :update
      delete :clear
      put :state
      put :all
    end
  end
  match 'batch_edits/:id' => 'batch_edits#add', :via => :put
  match 'batch_edits' => 'batch_edits#destroy_collection', :via => :delete

  resources :batch_uploads, only: [:new, :create], controller: 'batch_uploads'

  resources :collections, only: :show do # public landing show page
    member do
      get 'page/:page', action: :index
      get 'facet/:id', action: :facet, as: :dashboard_facet
      get :files
    end
  end

  # File Set routes
  scope :concern do
    resources :file_sets, only: [] do
      resource :fixity_checks, only: [:create]
      member do
        get 'stats'
      end
    end
  end

  resources :files, only: [] do
    member do
      get :citation, controller: :citations, action: :file, as: :citations
      get :stats, controller: :stats, action: :file, as: :stats
    end
  end

  # Generic work routes
  resources :works, only: [] do
    member do
      resources :transfers, as: :work_transfers, only: [:new, :create]
      resource :featured_work, only: [:create, :destroy]
      get :citation, controller: :citations, action: :work, as: :citations
      get :stats, controller: :stats, action: :work, as: :stats
      post 'trophy' => 'trophies#toggle_trophy' # used by hyrax/trophy.js
    end
  end

  # Depositors routes for proxy deposit
  post 'users/:user_id/depositors' => 'depositors#create', as: 'user_depositors'
  delete 'users/:user_id/depositors/:id' => 'depositors#destroy', as: 'user_depositor'
  get 'proxies' => 'depositors#index', as: 'depositors'

  resources :featured_work_lists, path: 'featured_works', only: :create

  # Messages
  resources :notifications, only: [:destroy, :index] do
    collection do
      delete 'delete_all'
    end
  end
  if Hyrax.config.realtime_notifications?
    namespace :notifications do
      # WebSocket for notifications
      mount ActionCable.server => 'endpoint', as: :endpoint
    end
  end

  # User profile
  resources :users, only: [:index, :show] do
    resources :operations, only: [:index, :show], controller: 'operations'
  end

  # Dashboard page
  resource :dashboard, controller: 'dashboard', only: [:show]
  resources :dashboard, only: [] do
    collection do
      get 'activity', action: :activity, as: :dashboard_activity
      resources :transfers, only: [:index, :destroy] do
        member do
          put 'accept'
          put 'reject'
        end
      end
    end
  end

  namespace :dashboard do
    resources :works, only: :index
    get 'works/facet/:id',  controller: 'works', action: :facet, as: 'works_facet'
    resources :collections do # Dashboard -> All Collections and CRUD
      member do
        get 'page/:page', action: :index
        get 'facet/:id', action: :facet, as: :dashboard_facet
        get :files
      end
      collection do
        put '', action: :update
        put :remove_member
      end
    end
    post 'collections/:id', controller: 'collection_members', action: :update_members
    post 'collections/:child_id/within', controller: 'nest_collections', action: 'create_relationship_within', as: 'create_nest_collection_within'
    get 'collections/:parent_id/under', controller: 'nest_collections', action: 'create_collection_under', as: 'create_subcollection_under'
    post 'collections/:parent_id/under', controller: 'nest_collections', action: 'create_relationship_under', as: 'create_nest_collection_under'
    post 'collections/:child_id/remove_parent/:parent_id', controller: 'nest_collections', action: 'remove_relationship_above', as: 'remove_parent_relationship_above'
    post 'collections/:parent_id/remove_child/:child_id', controller: 'nest_collections', action: 'remove_relationship_under', as: 'remove_child_relationship_under'
    resources :profiles, only: [:show, :edit, :update]
  end

  # Routes for user's works, collections, highlights and shares
  # Preserves existing behavior by maintaining paths to /dashboard
  # Routes actions to the various My controllers
  scope :dashboard do
    namespace :my do
      resources :works, only: :index
      get '/works/page/:page', controller: 'works', action: :index
      get 'works/facet/:id', controller: 'works', action: :facet, as: 'dashboard_works_facet'
      resources :collections, only: :index # Dashboard -> My Collections only
      get '/collections/page/:page',  controller: 'collections', action: :index
      get '/collections/facet/:id',   controller: 'my/collections', action: :facet, as: 'dashboard_collections_facet'
    end

    get '/highlights',            controller: 'my/highlights', action: :index, as: 'dashboard_highlights'
    get '/highlights/page/:page', controller: 'my/highlights', action: :index
    get '/highlights/facet/:id',  controller: 'my/highlights', action: :facet, as: 'dashboard_highlights_facet'

    get '/shares',            controller: 'my/shares', action: :index, as: 'dashboard_shares'
    get '/shares/page/:page', controller: 'my/shares', action: :index
    get '/shares/facet/:id',  controller: 'my/shares', action: :facet, as: 'dashboard_shares_facet'
    scope :collections do
      get '/permission_template/new' => 'admin/permission_templates#new', as: :new_dashboard_collection_permission_template
      get '/:collection_id/permission_template/edit' => 'admin/permission_templates#edit', as: :edit_dashboard_collection_permission_template
      get '/:collection_id/permission_template' => 'admin/permission_templates#show', as: :dashboard_collection_permission_template
      patch '/:collection_id/permission_template' => 'admin/permission_templates#update'
      put '/:collection_id/permission_template' => 'admin/permission_templates#update'
      delete '/:collection_id/permission_template' => 'admin/permission_templates#destroy'
      post '/:collection_id/permission_template' => 'admin/permission_templates#create'
    end
  end

  # Contact form routes
  post 'contact' => 'contact_form#create', as: :contact_form_index
  get 'contact' => 'contact_form#new'

  get 'single_use_link/show/:id' => 'single_use_links_viewer#show', as: :show_single_use_link
  get 'single_use_link/download/:id' => 'single_use_links_viewer#download', as: :download_single_use_link
  post 'single_use_link/generate_download/:id' => 'single_use_links#create_download', as: :generate_download_single_use_link
  post 'single_use_link/generate_show/:id' => 'single_use_links#create_show', as: :generate_show_single_use_link
  get 'single_use_link/generated/:id' => 'single_use_links#index', as: :generated_single_use_links
  delete 'single_use_link/:id/delete/:link_id' => 'single_use_links#destroy', as: :delete_single_use_link

  resources :embargoes, controller: 'embargoes', only: [:index, :edit, :destroy] do
    collection do
      patch :update
    end
  end

  resources :leases, controller: 'leases', only: [:index, :edit, :destroy] do
    collection do
      patch :update
    end
  end

  # Permissions routes
  scope :concern do
    resources :permissions, only: [] do
      member do
        get :confirm
        post :copy
        get :confirm_access
        post :copy_access
      end
    end
  end

  # API routes
  if Hyrax.config.arkivo_api?
    namespace :api do
      if defined?(Hyrax::ArkivoConstraint)
        constraints Hyrax::ArkivoConstraint do
          resources :items, except: [:index, :edit, :new], defaults: { format: :json }
        end
      end

      get 'zotero' => 'zotero#initiate', as: :zotero_initiate
      get 'zotero/callback' => 'zotero#callback', as: :zotero_callback
    end
  end

  namespace :admin do
    resources :admin_sets do
      member do
        get :files
      end
      resource :permission_template
    end
    resources :users, only: [:index]
    resources :permission_template_accesses, only: :destroy
    resource 'stats', only: [:show]
    resources :features, only: [:index] do
      resources :strategies, only: [:update, :destroy]
    end
    resources :workflows
    resources :workflow_roles
    resource :appearance
    resources :collection_types, except: :show
    resources :collection_type_participants, only: [:create, :destroy]
  end

  resources :content_blocks, only: [] do
    member do
      patch :update
    end
    collection do
      get :edit
    end
  end
  resources :pages, only: [] do
    member do
      patch :update
    end
    collection do
      get :edit
    end
  end
  get 'about' => 'pages#show', key: 'about'
  get 'help' => 'pages#show', key: 'help'
  get 'terms' => 'pages#show', key: 'terms'
  get 'agreement' => 'pages#show', key: 'agreement'

app/models/concerns/hyrax/ability/admin_set_ability.rb
module Hyrax
  module Ability
    module AdminSetAbility
      def admin_set_abilities # rubocop:disable Metrics/MethodLength
        if admin?
          can :manage, AdminSet
          can :manage_any, AdminSet
          can :create_any, AdminSet
          can :view_admin_show_any, AdminSet
        else
          can :manage_any, AdminSet if Hyrax::Collections::PermissionsService.can_manage_any_admin_set?(ability: self)
          can [:create_any, :create], AdminSet if Hyrax::CollectionTypes::PermissionsService.can_create_admin_set_collection_type?(ability: self)
          can :view_admin_show_any, AdminSet if Hyrax::Collections::PermissionsService.can_view_admin_show_for_any_admin_set?(ability: self)

          can [:edit, :update, :destroy], AdminSet do |admin_set| # for test by solr_doc, see solr_document_ability.rb
            test_edit(admin_set.id)
          end

          can :deposit, AdminSet do |admin_set| # for test by solr_doc, see collection_ability.rb
            Hyrax::Collections::PermissionsService.can_deposit_in_collection?(ability: self, collection_id: admin_set.id)
          end

          can :view_admin_show, AdminSet do |admin_set| # admin show page # for test by solr_doc, see collection_ability.rb
            Hyrax::Collections::PermissionsService.can_view_admin_show_for_collection?(ability: self, collection_id: admin_set.id)
          end

          # TODO: I don't think these are needed anymore since there isn't a public show page.  Should be checking :view_admin_show ability
          can :read, AdminSet do |admin_set| # for test by solr_doc, see solr_document_ability.rb
            test_read(admin_set.id)
          end
        end

        # TODO: I'm not sure why this is checked with AdminSet abilities.  It was before the refactor and since I'm not sure what the connection is, I left it here.
        can :review, :submissions do
          can_review_submissions?
        end
      end
    end
  end
end

app/models/concerns/hyrax/ability/collection_ability.rb
module Hyrax
  module Ability
    module CollectionAbility
      def collection_abilities # rubocop:disable Metrics/MethodLength, Metrics/AbcSize
        if admin?
          can :manage, Collection
          can :manage_any, Collection
          can :create_any, Collection
          can :view_admin_show_any, Collection
        else
          can :manage_any, Collection if Hyrax::Collections::PermissionsService.can_manage_any_collection?(ability: self)
          can :create_any, Collection if Hyrax::CollectionTypes::PermissionsService.can_create_any_collection_type?(ability: self)
          can :view_admin_show_any, Collection if Hyrax::Collections::PermissionsService.can_view_admin_show_for_any_collection?(ability: self)

          can [:edit, :update, :destroy], Collection do |collection| # for test by solr_doc, see solr_document_ability.rb
            test_edit(collection.id)
          end

          can :deposit, Collection do |collection|
            Hyrax::Collections::PermissionsService.can_deposit_in_collection?(ability: self, collection_id: collection.id)
          end
          can :deposit, ::SolrDocument do |solr_doc|
            Hyrax::Collections::PermissionsService.can_deposit_in_collection?(ability: self, collection_id: solr_doc.id) # checks collections and admin_sets
          end

          can :view_admin_show, Collection do |collection| # admin show page
            Hyrax::Collections::PermissionsService.can_view_admin_show_for_collection?(ability: self, collection_id: collection.id)
          end
          can :view_admin_show, ::SolrDocument do |solr_doc| # admin show page
            Hyrax::Collections::PermissionsService.can_view_admin_show_for_collection?(ability: self, collection_id: solr_doc.id) # checks collections and admin_sets
          end

          can :read, Collection do |collection| # public show page  # for test by solr_doc, see solr_document_ability.rb
            test_read(collection.id)
          end
        end
      end
    end
  end
end

app/models/concerns/hyrax/ability/collection_type_ability.rb
module Hyrax
  module Ability
    module CollectionTypeAbility
      def collection_type_abilities
        if admin?
          can :manage, CollectionType
          can :create_collection_type, CollectionType
        else
          can :create_collection_of_type, CollectionType do |collection_type|
            Hyrax::CollectionTypes::PermissionsService.can_create_collection_of_type?(user: current_user, collection_type: collection_type)
          end
        end
      end
    end
  end
end

app/models/concerns/hyrax/ability/permission_template_ability.rb
module Hyrax
  module Ability
    module PermissionTemplateAbility
      def permission_template_abilities
        if admin?
          can :manage, [Hyrax::PermissionTemplate, Hyrax::PermissionTemplateAccess]
        else
          can [:create, :edit, :update, :destroy], Hyrax::PermissionTemplate do |template|
            test_edit(template.source_id)
          end
          can [:create, :edit, :update, :destroy], Hyrax::PermissionTemplateAccess do |access|
            test_edit(access.permission_template.source_id)
          end
        end
      end
    end
  end
end

app/models/concerns/hyrax/ability/solr_document_ability.rb
module Hyrax
  module Ability
    module SolrDocumentAbility
      def solr_document_abilities
        if admin?
          can [:manage], ::SolrDocument
        else
          can [:edit, :update, :destroy], ::SolrDocument do |solr_doc|
            test_edit(solr_doc.id)
          end
          can :read, ::SolrDocument do |solr_doc|
            test_read(solr_doc.id)
          end
        end
      end
    end
  end
end

app/models/concerns/hyrax/basic_metadata.rb
module Hyrax
  # An optional model mixin to define some simple properties. This must be mixed
  # after all other properties are defined because no other properties will
  # be defined once  accepts_nested_attributes_for is called
  module BasicMetadata
    extend ActiveSupport::Concern

    included do
      property :label, predicate: ActiveFedora::RDF::Fcrepo::Model.downloadFilename, multiple: false

      property :relative_path, predicate: ::RDF::URI.new('http://scholarsphere.psu.edu/ns#relativePath'), multiple: false

      property :import_url, predicate: ::RDF::URI.new('http://scholarsphere.psu.edu/ns#importUrl'), multiple: false
      property :resource_type, predicate: ::RDF::Vocab::DC.type
      property :creator, predicate: ::RDF::Vocab::DC11.creator
      property :contributor, predicate: ::RDF::Vocab::DC11.contributor
      property :description, predicate: ::RDF::Vocab::DC11.description
      property :keyword, predicate: ::RDF::Vocab::DC11.relation
      # Used for a license
      property :license, predicate: ::RDF::Vocab::DC.rights

      # This is for the rights statement
      property :rights_statement, predicate: ::RDF::Vocab::EDM.rights
      property :publisher, predicate: ::RDF::Vocab::DC11.publisher
      property :date_created, predicate: ::RDF::Vocab::DC.created
      property :subject, predicate: ::RDF::Vocab::DC11.subject
      property :language, predicate: ::RDF::Vocab::DC11.language
      property :identifier, predicate: ::RDF::Vocab::DC.identifier
      property :based_near, predicate: ::RDF::Vocab::FOAF.based_near, class_name: Hyrax::ControlledVocabularies::Location
      property :related_url, predicate: ::RDF::RDFS.seeAlso
      property :bibliographic_citation, predicate: ::RDF::Vocab::DC.bibliographicCitation
      property :source, predicate: ::RDF::Vocab::DC.source

      id_blank = proc { |attributes| attributes[:id].blank? }

      class_attribute :controlled_properties
      self.controlled_properties = [:based_near]
      accepts_nested_attributes_for :based_near, reject_if: id_blank, allow_destroy: true
    end
  end
end

app/views/hyrax/file_sets/_asset_permissions_denial_flash.html.erb
The file(s)
<%=
  total_shown = 20
  file_sets.first(total_shown)
           .map { |fs| link_to(fs, file_set_url(fs)) }
           .tap { |fs| fs << '...' if file_sets.length > total_shown }
           .join(', ')
%>
 could not be updated.  You do not have sufficient privileges to edit it.

app/views/hyrax/file_sets/_asset_saved_flash.html.erb
The file(s)
<%=
  total_shown = 20
  file_sets.first(total_shown)
           .map { |fs| link_to(fs, file_set_url(fs)) }
           .tap { |fs| fs << '...' if file_sets.length > total_shown }
           .join(', ')
%>
 have been saved.

app/views/hyrax/file_sets/_asset_updated_flash.html.erb
The file <%= link_to(file_set, hyrax.file_set_url(file_set)) %> has been updated.

app/views/hyrax/file_sets/_descriptions.html.erb
<div id="descriptions_display" class="tab-pane active">
  <%= simple_form_for [hyrax, @form], html: { multipart: true } do |f| %>
    <%= hidden_field_tag('redirect_tab', 'descriptions') %>
    <h1>Descriptions</h1>
      <% f.object.terms.each do |term| %>
        <%= render_edit_field_partial(term, f: f) %>
      <% end %>
    <div>
      <%= button_tag class: 'btn btn-primary btn-lg', id: "upload_submit", name: "update_descriptions" do %>
        <i class="glyphicon glyphicon-floppy-disk"></i> Save Descriptions
      <% end %>
    </div>
  <% end %>
</div>

app/views/hyrax/file_sets/_file_set_title.erb
<% presenter.title.each_with_index do |title, index| %>
    <% if index == 0 %>
        <h1 class="ensure-wrapped">
            <%= title %> <%= presenter.permission_badge %>
        </h1>
    <% else %>
        <h1 class="ensure-wrapped"><%= title %></h1>
    <% end %>
<% end %>

app/views/hyrax/file_sets/_form.html.erb
<%= simple_form_for [main_app, curation_concern], html: { multipart: true } do |f| %>
  <fieldset class="required">
    <span class="control-label">
      <%= label_tag 'file_set[title][]', t('.title'),  class: "string optional" %>
    </span>
    <%= text_field_tag 'file_set[title][]', curation_concern.title.first, class: 'form-control', required: true %>
  </fieldset>

  <div class="row">
    <div class="col-md-12 form-actions">
      <%= f.submit(
        (curation_concern.persisted? ? t('.save') : t('.attach_to', parent: @parent.human_readable_type)),
        class: 'btn btn-primary'
      ) %>
      <%= link_to t('.cancel'), parent_path(@parent), class: 'btn btn-link' %>
    </div>
  </div>
<% end %>

app/views/hyrax/file_sets/_groups_description.html.erb
<p><%= t('.description_html', institution_name: institution_name, application_name: application_name) %></p>

app/views/hyrax/file_sets/_permission.html.erb
  <div id="permissions_display" class="tab-pane">
    <%= simple_form_for [main_app, file_set],
                        html: { multipart: true,
                                id: 'permission',
                                data: { param_key: file_set.model_name.param_key }
                              } do |f| %>
      <%= hidden_field_tag('redirect_tab', 'permissions') %>
      <%= render "permission_form", f: f %>
      <div id="permissions_submit">
        <%= button_tag type: 'submit', class: 'btn btn-primary', onclick: "confirmation_needed = false;", id: "upload_submit", name: "update_permission" do %>
          <%= t('.save') %>
        <% end %>
      </div>
  <% end %>
</div><!-- /#permissions_display -->

app/views/hyrax/file_sets/_show_actions.html.erb
<div class="form-actions">
  <% if Hyrax.config.analytics? %>
    <%= link_to "Analytics", @presenter.stats_path, id: 'stats', class: 'btn btn-default' %>
  <% end %>

  <% if @presenter.editor? %>
      <%= link_to "Edit This #{@presenter.human_readable_type}", edit_polymorphic_path([main_app, @presenter]),
                  class: 'btn btn-default' %>
      <%= link_to "Delete This #{@presenter.human_readable_type}", [main_app, @presenter],
                  class: 'btn btn-danger', data: { confirm: "Delete this #{@presenter.human_readable_type}?" },
                  method: :delete %>
  <% end %>

  <%= render 'social_media' %>
</div>

app/views/hyrax/file_sets/_show_characterization_details.html.erb
<% @presenter.characterization_metadata.keys.each do |term| %>
  <div>
    <% additional_values = @presenter.secondary_characterization_values(term) %>
    <%= @presenter.label_for_term(term) %>: <%= sanitize @presenter.primary_characterization_values(term).join("<br />") %>
    <% unless additional_values.empty? %>
      <%= render partial: "extra_fields_modal", locals: { name: term, values: additional_values } %>
    <% end %>
  </div>
<% end %>

app/views/hyrax/file_sets/_show_details.html.erb
<h2>File Details</h2>
<dl class="dl-horizontal file-show-term file-show-details">
  <dt>Depositor</dt>
  <dd itemprop="accountablePerson" itemscope itemtype="http://schema.org/Person"><span itemprop="name"><%= link_to_profile @presenter.depositor %></span></dd>
  <dt>Date Uploaded</dt>
  <dd itemprop="datePublished"><%= @presenter.date_uploaded %></dd>
  <dt>Date Modified</dt>
  <dd itemprop="dateModified"><%= @presenter.date_modified %></dd>
  <dt>Fixity Check</dt>
  <dd><%= @presenter.fixity_check_status %></dd>
  <dt>Characterization</dt>
  <dd>
    <% if @presenter.characterized? %>
      <%= render 'show_characterization_details' %>
    <% else %>
      not yet characterized
    <% end %>
  </dd>
</dl>

app/views/hyrax/file_sets/_single_use_links.html.erb
<h3><%= t('hyrax.single_use_links.title') %></h3>
<table class="table table-striped table-condensed <%= dom_class(presenter) %> single-use-links">
  <tbody data-url="<%= hyrax.generated_single_use_links_path(presenter) %>">
    <% if presenter.single_use_links.empty? %>
      <tr><td><%= t('hyrax.single_use_links.table.no_links') %></td></tr>
    <% else %>
      <%= render 'single_use_link_rows', single_use_links: presenter.single_use_links %>
    <% end %>
  </tbody>
</table>
<div class="form_actions">
  <%= link_to t('hyrax.single_use_links.button'),
              hyrax.generate_download_single_use_link_path(presenter),
              class: 'btn btn-default generate-single-use-link' %>
</div>

app/views/hyrax/file_sets/edit.html.erb
<% provide :page_title, curation_concern_page_title(curation_concern) %>
<% provide :page_header do %>
  <h1><span class="fa fa-edit" aria-hidden="true"></span><%= t('.header', file_set: curation_concern) %></h1>
<% end %>

<div class="row">
  <div class="col-xs-12 col-sm-4">
    <%= media_display curation_concern.to_presenter %>
  </div>
  <div class="col-xs-12 col-sm-8">
    <div class="panel panel-default tabs">
      <ul class="nav nav-tabs" role="tablist">
        <li id="edit_descriptions_link" class="active">
          <a href="#descriptions_display" data-toggle="tab"><i class="fa fa-tags" aria-hidden="true"></i></span> <%= t('.descriptions') %></a>
        </li>
        <li id="edit_versioning_link">
          <a href="#versioning_display" data-toggle="tab"><i class="fa fa-sitemap" aria-hidden="true"></i> <%= t('.versions') %></a>
        </li>
        <li id="edit_permissions_link">
          <a href="#permissions_display" data-toggle="tab"><i class="fa fa-key" aria-hidden="true"></i> <%= t('.permissions') %></a>
        </li>
      </ul>
      <div class="panel-body">
        <div class="tab-content">
          <div id="descriptions_display" class="tab-pane active">
            <h2><%= t('.descriptions') %></h2>
            <%= render "form" %>
          </div>
          <%= render "permission", file_set: curation_concern %>
          <%= render "versioning", file_set: curation_concern %>
        </div>
      </div>
    </div><!-- /.col-sm-8 -->
  </div><!-- /.row -->
</div>

app/views/hyrax/file_sets/show.html.erb
<% provide :page_title, @presenter.page_title %>
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-sm-4">
      <%= media_display @presenter %>
      <%= render 'show_actions', presenter: @presenter %>
      <%= render 'single_use_links', presenter: @presenter if @presenter.editor? %>
    </div>
    <div itemscope itemtype="<%= @presenter.itemtype %>" class="col-xs-12 col-sm-8">
      <header>
        <%= render 'file_set_title', presenter: @presenter %>
      </header>

      <%# TODO: render 'show_descriptions' See https://github.com/samvera/hyrax/issues/1481 %>
      <%= render 'show_details' %>
      <%= render 'hyrax/users/activity_log', events: @presenter.events %>
    </div><!-- /columns second -->
  </div> <!-- /.row -->
</div><!-- /.container-fluid -->