config/routes.rb
Hyrax::Engine.routes.draw do
  # Downloads controller route
  resources :homepage, only: 'index'

  # Route the home page as the root
  root to: 'homepage#index'

  # Handle routes that existed in Hyrax < 7
  #   e.g. https://scholarsphere.psu.edu/files/gm80hv36p
  get '/files/:id', to: redirect('/concern/generic_works/%{id}')

  resources :downloads, only: :show

  # ResourceSync routes
  get '/.well-known/resourcesync' => 'resource_sync#source_description', as: :source_description
  get '/capabilitylist' => 'resource_sync#capability_list', as: :capability_list
  get '/resourcelist' => 'resource_sync#resource_list', as: :resource_list
  get '/changelist' => 'resource_sync#change_list', as: :change_list

  delete '/uploads/:id', to: 'uploads#destroy', as: :uploaded_file
  post '/uploads', to: 'uploads#create'
  # This is a hack that is required because the rails form the uploader is on
  # sets the _method parameter to patch when the work already exists.
  # Eventually it would be good to update the javascript so that it doesn't
  # submit the form, just the file and always uses POST.
  patch '/uploads', to: 'uploads#create'

  match 'batch_edits/clear' => 'batch_edits#clear', as: :batch_edits_clear, via: [:get, :post]
  resources :batch_edits, only: [:index] do
    member do
      delete :destroy
    end
    collection do
      get :index
      get :edit
      put :update
      delete :clear
      put :state
      put :all
    end
  end
  match 'batch_edits/:id' => 'batch_edits#add', :via => :put
  match 'batch_edits' => 'batch_edits#destroy_collection', :via => :delete

  resources :batch_uploads, only: [:new, :create], controller: 'batch_uploads'

  resources :collections, only: :show do # public landing show page
    member do
      get 'page/:page', action: :index
      get 'facet/:id', action: :facet, as: :dashboard_facet
      get :files
    end
  end

  # File Set routes
  scope :concern do
    resources :file_sets, only: [] do
      resource :fixity_checks, only: [:create]
      member do
        get 'stats'
      end
    end
  end

  resources :files, only: [] do
    member do
      get :citation, controller: :citations, action: :file, as: :citations
      get :stats, controller: :stats, action: :file, as: :stats
    end
  end

  # Generic work routes
  resources :works, only: [] do
    member do
      resources :transfers, as: :work_transfers, only: [:new, :create]
      resource :featured_work, only: [:create, :destroy]
      get :citation, controller: :citations, action: :work, as: :citations
      get :stats, controller: :stats, action: :work, as: :stats
      post 'trophy' => 'trophies#toggle_trophy' # used by hyrax/trophy.js
    end
  end

  # Depositors routes for proxy deposit
  post 'users/:user_id/depositors' => 'depositors#create', as: 'user_depositors'
  delete 'users/:user_id/depositors/:id' => 'depositors#destroy', as: 'user_depositor'
  get 'proxies' => 'depositors#index', as: 'depositors'

  resources :featured_work_lists, path: 'featured_works', only: :create

  # Messages
  resources :notifications, only: [:destroy, :index] do
    collection do
      delete 'delete_all'
    end
  end
  if Hyrax.config.realtime_notifications?
    namespace :notifications do
      # WebSocket for notifications
      mount ActionCable.server => 'endpoint', as: :endpoint
    end
  end

  # User profile
  resources :users, only: [:index, :show] do
    resources :operations, only: [:index, :show], controller: 'operations'
  end

  # Dashboard page
  resource :dashboard, controller: 'dashboard', only: [:show]
  resources :dashboard, only: [] do
    collection do
      get 'activity', action: :activity, as: :dashboard_activity
      resources :transfers, only: [:index, :destroy] do
        member do
          put 'accept'
          put 'reject'
        end
      end
    end
  end

  namespace :dashboard do
    resources :works, only: :index
    get 'works/facet/:id',  controller: 'works', action: :facet, as: 'works_facet'
    resources :collections do # Dashboard -> All Collections and CRUD
      member do
        get 'page/:page', action: :index
        get 'facet/:id', action: :facet, as: :dashboard_facet
        get :files
      end
      collection do
        put '', action: :update
        put :remove_member
      end
    end
    post 'collections/:id', controller: 'collection_members', action: :update_members
    post 'collections/:child_id/within', controller: 'nest_collections', action: 'create_relationship_within', as: 'create_nest_collection_within'
    get 'collections/:parent_id/under', controller: 'nest_collections', action: 'create_collection_under', as: 'create_subcollection_under'
    post 'collections/:parent_id/under', controller: 'nest_collections', action: 'create_relationship_under', as: 'create_nest_collection_under'
    post 'collections/:child_id/remove_parent/:parent_id', controller: 'nest_collections', action: 'remove_relationship_above', as: 'remove_parent_relationship_above'
    post 'collections/:parent_id/remove_child/:child_id', controller: 'nest_collections', action: 'remove_relationship_under', as: 'remove_child_relationship_under'
    resources :profiles, only: [:show, :edit, :update]
  end

  # Routes for user's works, collections, highlights and shares
  # Preserves existing behavior by maintaining paths to /dashboard
  # Routes actions to the various My controllers
  scope :dashboard do
    namespace :my do
      resources :works, only: :index
      get '/works/page/:page', controller: 'works', action: :index
      get 'works/facet/:id', controller: 'works', action: :facet, as: 'dashboard_works_facet'
      resources :collections, only: :index # Dashboard -> My Collections only
      get '/collections/page/:page',  controller: 'collections', action: :index
      get '/collections/facet/:id',   controller: 'my/collections', action: :facet, as: 'dashboard_collections_facet'
    end

    get '/highlights',            controller: 'my/highlights', action: :index, as: 'dashboard_highlights'
    get '/highlights/page/:page', controller: 'my/highlights', action: :index
    get '/highlights/facet/:id',  controller: 'my/highlights', action: :facet, as: 'dashboard_highlights_facet'

    get '/shares',            controller: 'my/shares', action: :index, as: 'dashboard_shares'
    get '/shares/page/:page', controller: 'my/shares', action: :index
    get '/shares/facet/:id',  controller: 'my/shares', action: :facet, as: 'dashboard_shares_facet'
    scope :collections do
      get '/permission_template/new' => 'admin/permission_templates#new', as: :new_dashboard_collection_permission_template
      get '/:collection_id/permission_template/edit' => 'admin/permission_templates#edit', as: :edit_dashboard_collection_permission_template
      get '/:collection_id/permission_template' => 'admin/permission_templates#show', as: :dashboard_collection_permission_template
      patch '/:collection_id/permission_template' => 'admin/permission_templates#update'
      put '/:collection_id/permission_template' => 'admin/permission_templates#update'
      delete '/:collection_id/permission_template' => 'admin/permission_templates#destroy'
      post '/:collection_id/permission_template' => 'admin/permission_templates#create'
    end
  end

  # Contact form routes
  post 'contact' => 'contact_form#create', as: :contact_form_index
  get 'contact' => 'contact_form#new'

  get 'single_use_link/show/:id' => 'single_use_links_viewer#show', as: :show_single_use_link
  get 'single_use_link/download/:id' => 'single_use_links_viewer#download', as: :download_single_use_link
  post 'single_use_link/generate_download/:id' => 'single_use_links#create_download', as: :generate_download_single_use_link
  post 'single_use_link/generate_show/:id' => 'single_use_links#create_show', as: :generate_show_single_use_link
  get 'single_use_link/generated/:id' => 'single_use_links#index', as: :generated_single_use_links
  delete 'single_use_link/:id/delete/:link_id' => 'single_use_links#destroy', as: :delete_single_use_link

  resources :embargoes, controller: 'embargoes', only: [:index, :edit, :destroy] do
    collection do
      patch :update
    end
  end

  resources :leases, controller: 'leases', only: [:index, :edit, :destroy] do
    collection do
      patch :update
    end
  end

  # Permissions routes
  scope :concern do
    resources :permissions, only: [] do
      member do
        get :confirm
        post :copy
        get :confirm_access
        post :copy_access
      end
    end
  end

  # API routes
  if Hyrax.config.arkivo_api?
    namespace :api do
      if defined?(Hyrax::ArkivoConstraint)
        constraints Hyrax::ArkivoConstraint do
          resources :items, except: [:index, :edit, :new], defaults: { format: :json }
        end
      end

      get 'zotero' => 'zotero#initiate', as: :zotero_initiate
      get 'zotero/callback' => 'zotero#callback', as: :zotero_callback
    end
  end

  namespace :admin do
    resources :admin_sets do
      member do
        get :files
      end
      resource :permission_template
    end
    resources :users, only: [:index]
    resources :permission_template_accesses, only: :destroy
    resource 'stats', only: [:show]
    resources :features, only: [:index] do
      resources :strategies, only: [:update, :destroy]
    end
    resources :workflows
    resources :workflow_roles
    resource :appearance
    resources :collection_types, except: :show
    resources :collection_type_participants, only: [:create, :destroy]
  end

  resources :content_blocks, only: [] do
    member do
      patch :update
    end
    collection do
      get :edit
    end
  end
  resources :pages, only: [] do
    member do
      patch :update
    end
    collection do
      get :edit
    end
  end
  get 'about' => 'pages#show', key: 'about'
  get 'help' => 'pages#show', key: 'help'
  get 'terms' => 'pages#show', key: 'terms'
  get 'agreement' => 'pages#show', key: 'agreement'

app/models/admin_set.rb
# There is an interplay between an AdminSet and a PermissionTemplate. Given
# that AdminSet is an ActiveFedora::Base and PermissionTemplate is ActiveRecord::Base
# we don't have the usual :has_many or :belongs_to methods to assist in defining that
# relationship. However, from a conceptual standpoint:
#
# * An AdminSet has_one :permission_tempate
# * A PermissionTemplate belongs_to :admin_set
#
# When an object is added as a member of an AdminSet, the AdminSet's associated
# PermissionTemplate is applied to that object (e.g. some of the object's attributes
# are updated as per the rules of the permission template)
#
# @see Hyrax::PermissionTemplate
# @see Hyrax::AdminSetService
# @see Hyrax::Forms::PermissionTemplateForm for validations and creation process
# @see Hyrax::DefaultAdminSetActor
# @see Hyrax::ApplyPermissionTemplateActor
class AdminSet < ActiveFedora::Base
  include Hydra::AccessControls::WithAccessRight
  include Hyrax::Noid
  include Hyrax::HumanReadableType
  include Hyrax::HasRepresentative

  DEFAULT_ID = 'admin_set/default'.freeze
  DEFAULT_TITLE = ['Default Admin Set'].freeze
  DEFAULT_WORKFLOW_NAME = Hyrax.config.default_active_workflow_name

  validates_with Hyrax::HasOneTitleValidator
  class_attribute :human_readable_short_description
  self.indexer = Hyrax::AdminSetIndexer
  property :title, predicate: ::RDF::Vocab::DC.title do |index|
    index.as :stored_searchable, :facetable
  end
  property :description, predicate: ::RDF::Vocab::DC.description do |index|
    index.as :stored_searchable
  end

  property :creator, predicate: ::RDF::Vocab::DC11.creator do |index|
    index.as :symbol
  end
  has_many :members,
           predicate:  Hyrax.config.admin_set_predicate,
           class_name: 'ActiveFedora::Base'
  # rubocop:enable Rails/HasManyOrHasOneDependent

  before_destroy :check_if_not_default_set, :check_if_empty
  after_destroy :destroy_permission_template

  def self.default_set?(id)
    id == DEFAULT_ID
  end

  def default_set?
    self.class.default_set?(id)
  end

  # Creates the default AdminSet and an associated PermissionTemplate with workflow
  def self.find_or_create_default_admin_set_id
    Hyrax::AdminSetCreateService.create_default_admin_set(admin_set_id: DEFAULT_ID, title: DEFAULT_TITLE) unless exists?(DEFAULT_ID)
    DEFAULT_ID
  end

  def to_s
    title.present? ? title : 'No Title'
  end

  # @api public
  # A bit of an analogue for a `has_one :admin_set` as it crosses from Fedora to the DB
  # @return [Hyrax::PermissionTemplate]
  # @raise [ActiveRecord::RecordNotFound]
  def permission_template
    Hyrax::PermissionTemplate.find_by!(source_id: id)
  end

  # @api public
  #
  # @return [Sipity::Workflow]
  # @raise [ActiveRecord::RecordNotFound]
  def active_workflow
    Sipity::Workflow.find_active_workflow_for(admin_set_id: id)
  end

  # Calculate and update who should have edit access based on who
  # has "manage" access in the PermissionTemplateAccess
  def reset_access_controls!
    # NOTE: This is different from Collections in that it doesn't update read access based on visibility.
    #       See also app/models/concerns/hyrax/collection_behavior.rb#reset_access_controls!
    update!(edit_users: permission_template_edit_users,
            edit_groups: permission_template_edit_groups,
            read_users: permission_template_read_users,
            read_groups: permission_template_read_groups)
  end

  private

    def permission_template_edit_users
      permission_template.agent_ids_for(access: 'manage', agent_type: 'user')
    end

    def permission_template_edit_groups
      permission_template.agent_ids_for(access: 'manage', agent_type: 'group')
    end

    def permission_template_read_users
      (permission_template.agent_ids_for(access: 'view', agent_type: 'user') +
          permission_template.agent_ids_for(access: 'deposit', agent_type: 'user')).uniq
    end

    def permission_template_read_groups
      (permission_template.agent_ids_for(access: 'view', agent_type: 'group') +
        permission_template.agent_ids_for(access: 'deposit', agent_type: 'group')).uniq -
        [::Ability.registered_group_name, ::Ability.public_group_name]
    end

    def destroy_permission_template
      permission_template.destroy
    rescue ActiveRecord::RecordNotFound
      true
    end

    def check_if_empty
      return true if members.empty?
      errors[:base] << I18n.t('hyrax.admin.admin_sets.delete.error_not_empty')
      throw :abort
    end

    def check_if_not_default_set
      return true unless default_set?
      errors[:base] << I18n.t('hyrax.admin.admin_sets.delete.error_default_set')
      throw :abort
    end
end

app/views/hyrax/admin/admin_sets/_form.html.erb
    <div class="panel panel-default tabs" id="admin-set-controls">
      <ul class="nav nav-tabs" role="tablist">
        <li class="active">
          <a href="#description" role="tab" data-toggle="tab"><%= t('.tabs.description') %></a>
        </li>
        <% if @form.persisted? %>
          <li>
            <a href="#participants" role="tab" data-toggle="tab"><%= t('.tabs.participants') %></a>
          </li>
          <li>
            <a href="#visibility" role="tab" data-toggle="tab"><%= t('.tabs.visibility') %></a>
          </li>
          <li>
            <a href="#workflow" role="tab" data-toggle="tab"><%= t('.tabs.workflow') %></a>
          </li>
        <% end %>
      </ul>
      <div class="tab-content">
        <div id="description" class="tab-pane active">
          <div class="panel panel-default labels">
            <%= simple_form_for @form, url: [hyrax, :admin, @form] do |f| %>
              <div class="panel-body">
                <%= render 'form_metadata', f: f %>

                <% if f.object.persisted? && f.object.member_ids.present? %>
                  <%# we're loading these values dynamically to speed page load %>
                  <%= f.input :thumbnail_id,
                              input_html: { data: { text: f.object.thumbnail_title } } %>
                <% end %>

              </div>

              <div class="panel-footer">
                <% cancel_path = f.object.persisted? ? hyrax.admin_admin_set_path(f.object) : hyrax.dashboard_collections_path %>
                <%= link_to t('.cancel'), cancel_path, class: 'btn btn-default pull-right' %>
                <%= f.button :submit, class: 'btn btn-primary pull-right' %>
              </div>
            <% end %>
          </div>
        </div>
        <% if @form.persisted? %>
          <%= render 'form_participants' %>
          <%= render 'form_visibility' %>
          <%= render 'form_workflow' %>
        <% end %>
      </div>
    </div>

app/views/hyrax/admin/admin_sets/_form_metadata.html.erb
<%= f.input :title %>
<%= f.input :description, as: :text %>

app/views/hyrax/admin/admin_sets/_form_participant_table.html.erb
                  <h3><%= t(".#{access}.title") %></h3>
                  <p><%= t(".#{access}.help") %></p>
                  <% if @form.permission_template.access_grants.select(&filter).any? %>
                    <table class="table table-striped share-status">
                      <thead>
                        <tr>
                          <th><%= t(".#{access}.agent_name") %></th>
                          <th><%= t(".#{access}.type") %></th>
                          <th><%= t(".#{access}.action") %></th>
                        </tr>
                      </thead>
                      <tbody>
                      <% @form.permission_template.access_grants.select(&filter).each do |g| %>
                        <tr>
                          <td data-agent="<%= g.agent_id %>"><%= g.label %></td>
                          <td><%= g.agent_type.titleize %></td>
                          <td>
                            <% if g.admin_group? && g.access == Hyrax::PermissionTemplateAccess::MANAGE %>
                              <%= button_to t(".#{access}.remove"), hyrax.admin_permission_template_access_path(g), method: :delete, class: 'btn btn-sm btn-danger disabled', disabled: true, title: t('hyrax.admin.admin_sets.form.permission_destroy_errors.admin_group') %>
                            <% else %>
                              <%= button_to t(".#{access}.remove"), hyrax.admin_permission_template_access_path(g), method: :delete, class: 'btn btn-sm btn-danger' %>
                            <% end %>
                          </td>
                        </tr>
                      <% end %>
                      </tbody>
                    </table>
                  <% else %>
                    <p><em><%= t(".#{access}.empty") %></em></p>
                  <% end %>
                  <%= button_tag t('.allow_all_registered'),
                                 class: 'btn btn-info',
                                 data: { behavior: 'add-registered-users' } if access == 'depositors' %>

app/views/hyrax/admin/admin_sets/_form_participants.html.erb
          <div id="participants" class="tab-pane">
            <div class="panel panel-default labels edit-sharing-tab">
              <div class="panel-body">
                <section class="section-add-sharing clearfix">
                  <h3><%= t('.add_participants') %></h3>
                  <% access_options = options_for_select([['Manager', 'manage'], ['Depositor', 'deposit'], ['Viewer', 'view']]) %>
                  <div class="sharing-row-form">
                    <%= simple_form_for @form.permission_template,
                        url: [hyrax, :admin, @form, :permission_template],
                        html: { id: 'group-participants-form', class: 'form-inline' } do |f| %>

                        <%= f.fields_for 'access_grants_attributes',
                            f.object.access_grants.build(agent_type: 'group'),
                            index: 0 do |builder| %>
                          <div class="form-group">
                            <label><%= t('.add_group') %></label>
                            <%= builder.hidden_field :agent_type %>
                            <%= builder.text_field :agent_id,
                                placeholder: "Search for a group...",
                                class: 'form-control' %>
                          </div>
                          <div class="form-group">
                            <label>as</label>
                            <%= builder.select :access,
                                access_options,
                                { prompt: "Select a role..." },
                                class: 'form-control' %>
                          </div>
                        <% end %>
                        <%= f.submit t('helpers.submit.hyrax_permission_template_access.create'), class: 'btn btn-info' %>

                    <% end %>
                  </div>

                  <div class="sharing-row-form">
                    <%= simple_form_for @form.permission_template,
                        url: [hyrax, :admin, @form, :permission_template],
                        html: { id: 'user-participants-form', class: 'form-inline add-users' } do |f| %>

                      <%= f.fields_for 'access_grants_attributes',
                                      f.object.access_grants.build(agent_type: 'user'),
                                      index: 0 do |builder| %>
                        <div class="form-group">
                          <label><%= t('.add_user') %></label>
                          <%= builder.hidden_field :agent_type %>
                          <%= builder.text_field :agent_id,
                                            placeholder: "Search for a user..." %>
                        </div>
                        <div class="form-group">
                          <label>as</label>
                          <%= builder.select :access,
                                      access_options,
                                      { prompt: "Select a role..." },
                                      class: 'form-control' %>
                        </div>
                      <% end %>
                      <%= f.submit t('helpers.submit.hyrax_permission_template_access.create'), class: 'btn btn-info' %>
                    <% end %>
                  </div>

                  <p class="help-block"><%= t('hyrax.admin.admin_sets.form.note') %></p>
                </section>

                <fieldset class="admin-set-participants section-collection-sharing">
                  <legend><%= t(".current_participants") %></legend>
                  <%= render 'form_participant_table', access: 'managers', filter: :manage? %>
                  <%= render 'form_participant_table', access: 'depositors', filter: :deposit? %>
                  <%= render 'form_participant_table', access: 'viewers', filter: :view? %>
                </fieldset>

              </div><!-- /.panel-body -->
            </div>
          </div>

app/views/hyrax/admin/admin_sets/_form_visibility.html.erb
          <div id="visibility" class="tab-pane">
            <div class="panel panel-default labels">
              <%= simple_form_for @form.permission_template,
                                  url: [hyrax, :admin, @form, :permission_template] do |f| %>
                <div class="panel-body">
                  <p><%= t('.page_description') %></p>
                  <h3><%= t('.release.title') %></h3>
                  <p><%= t('.release.description') %></p>
                  <div id="release-no-delay" class="radio">
                    <label>
                      <%= f.radio_button :release_period, Hyrax::PermissionTemplate::RELEASE_TEXT_VALUE_NO_DELAY %>
                      <%= t('.release.no_delay') %>
                    </label>
                  </div>
                  <div id="release-varies" class="radio">
                    <label>
                      <%= f.radio_button :release_period, '', checked: f.object.release_period.blank? || !f.object.release_varies.blank? %>
                      <%= t('.release.varies.description') %>
                    </label>
                    <ul>
                      <li class="radio form-inline">
                        <label>
                          <%= f.radio_button :release_varies, '' %>
                          <%= t('.release.varies.any') %>
                        </label>
                      </li>
                      <li class="radio form-inline">
                        <label>
                          <%= f.radio_button :release_varies, Hyrax::PermissionTemplate::RELEASE_TEXT_VALUE_BEFORE_DATE %>
                          <%= t('.release.varies.between') %>
                        </label>
                        <%= f.date_field :release_date, wrapper: :inline, class: 'datepicker form-control' %>
                      </li>
                      <li class="radio form-inline">
                        <label>
                          <%= f.radio_button :release_varies, Hyrax::PermissionTemplate::RELEASE_TEXT_VALUE_EMBARGO %>
                          <%= t('.release.varies.period') %>
                          <%= f.collection_select :release_embargo, f.object.embargo_options, :first, :last, prompt: t('.release.varies.embargo.select') %>
                        </label>
                      </li>
                    </ul>
                  </div>
                  <div id="release-fixed" class="radio form-inline">
                    <label>
                      <%= f.radio_button :release_period, Hyrax::PermissionTemplate::RELEASE_TEXT_VALUE_FIXED %>
                      <%= t('.release.fixed') %>
                    </label>
                    <%= f.date_field :release_date, wrapper: :inline, class: 'datepicker form-control' %>
                  </div>
                  <h3><%= t('.visibility.title') %></h3>
                  <p><%= t('.visibility.description') %></p>
                  <%# List each option in a <div class='radio'> tag %>
                  <%= f.collection_radio_buttons :visibility, f.object.visibility_options, :first, :last, item_wrapper_tag: :div, item_wrapper_class: 'radio' do |b| %>
                    <%# NOTE: Bug in simple_form causes nested labels: https://github.com/plataformatec/simple_form/issues/1190 This block is a workaround. %>
                    <% b.radio_button + b.text %>
                  <% end %>
                </div>
                <div class="panel-footer">
                  <%= link_to t('.cancel'), hyrax.admin_admin_sets_path, class: 'btn btn-default pull-right' %>
                  <%= f.button :submit, class: 'btn btn-primary pull-right' %>
                </div>
              <% end %>
            </div>
          </div>

app/views/hyrax/admin/admin_sets/_form_workflow.erb
                <div id="workflow" class="tab-pane">
                  <div class="panel panel-default labels">
                    <%= simple_form_for @form.permission_template,
                      url: [hyrax, :admin, @form, :permission_template],
                      html: { id: 'form_workflows' } do |f| %>
                      <% if f.object.available_workflows.any? %>
                        <div class="panel-body">
                          <p><%= t('.page_description') %></p>
                              <%= f.collection_radio_buttons :workflow_id, f.object.available_workflows, :id, :label, item_wrapper_tag: :div, item_wrapper_class: "radio" do |b| %>
                                <span><%= b.radio_button + b.object.label %></span>
                                <p><%= b.object.description %></p>
                              <% end %>
                        </div>
                        <div class="panel-footer">
                          <%= link_to t('.cancel'), hyrax.admin_admin_sets_path, class: 'btn btn-default pull-right'%>
                          <%= f.button :submit, class: 'btn btn-primary pull-right'%>
                        </div>
                      <% else %>
                        <div class="panel-body">
                          <p><%= t('.no_workflows') %></p>
                        </div>
                      <% end %>
                    <% end %>
                  </div>
                </div>

app/views/hyrax/admin/admin_sets/_show_actions.html.erb
    <% if can? :edit, presenter.solr_document %>
      <div class="panel-heading">
        <div class="row">
          <div class="col-sm-8">
            <h2 class="panel-title display-page"><%= presenter.to_s %></h2>
          </div>
          <div class="col-sm-4">
            <div class="pull-right">
              <%= link_to edit_admin_admin_set_path(presenter), class: 'btn btn-primary' do %>
                <span class="fa fa-edit" aria-hidden="true"></span> <%= t(:'helpers.action.edit') %>
              <% end %>
              <% if presenter.disable_delete? %>
                <span title="<%= presenter.disabled_message %>">
                  <%= link_to admin_admin_set_path(presenter), class: 'btn btn-danger disabled' do %>
                    <span class="fa fa-remove" aria-hidden="true"></span> <%= t(:'helpers.action.delete') %>
                  <% end %>
                </span>
              <% else %>
                <%= link_to admin_admin_set_path(presenter), class: 'btn btn-danger', data: { confirm: t('.confirm_delete'), method: :delete } do %>
                  <span class="fa fa-remove" aria-hidden="true"></span> <%= t(:'helpers.action.delete') %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>

app/views/hyrax/admin/admin_sets/_show_document_list.html.erb
<table class="table table-striped">
  <caption class="sr-only">List of items in this administrative set</caption>
  <thead>
  <tr>
    <th>&nbsp;</th>
    <th>Title</th>
    <th>Date Uploaded</th>
    <th>Visibility</th>
    <th>Status</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
    <%= render partial: 'show_document_list_row', collection: documents %>
  </tbody>
</table>

app/views/hyrax/admin/admin_sets/_sort_and_per_page.html.erb
<% if show_pagination? %>
  <div id="sortAndPerPage" class="sort-pagination clearfix">
    <%= render partial: "paginate_compact", object: @response %>
  </div>
<% end %>

app/views/hyrax/admin/admin_sets/edit.html.erb
<% provide :page_header do %>
  <h1><span class="fa fa-edit" aria-hidden="true"></span> <%= t('.header', title: @form.title) %></h1>
<% end %>

<div class="row">
  <div class="col-md-12">
    <%= render 'form' %>
  </div>
</div>

app/views/hyrax/admin/admin_sets/new.html.erb
<% provide :page_header do %>
  <h1><span class="fa fa-edit" aria-hidden="true"></span> <%= t('.header') %></h1>
<% end %>

<div class="row">
  <div class="col-md-12">
    <%= render 'form' %>
  </div>
</div>